### ISSUE TITLE
HTTParty.post is unusable

### ISSUE THREAD

**Issue by john-h-k** [jnunemaker/httparty#774]
#754 was a breaking change for us and ever since we have gotten `undefined method `+@' for ["Not found"]:Array` errors continuously whenever trying to use HTTParty

**Comment by TheSmartnik** [comment]
Could you please provide a reproduction example

**Comment by hs-ssamdani** [comment]
@john-h-k Were you able to fix this issue ? I am also getting this on HTTParty.get while passing query params.

**Comment by TheSmartnik** [comment]
I'm still waiting for any reproduction example. So, I could debug and fix it

**Comment by mikevoets** [comment]
> I'm still waiting for any reproduction example. So, I could debug and fix it

@TheSmartnik We're also getting this error after updating to 0.21.0. 

In our case, when we issue a request that responds with 422 Unprocessable Entity, the response `raw_body` is an empty list `[]`. When that body gets passed to `encode_text` and then as `text` to the `TextEncoder` initializer, the `@text = +text` operation on `lib/httparty/text_encoder.rb:8` results in the error that is reported in the opening post.

Hope that helps.

**Comment by jaredbeck** [comment]
We would like to upgrade to 0.21 per the security advisory, but are concerned about this issue, despite being unable to reproduce it using the following script. @mikevoets, could you please use this script as a starting point to give @TheSmartnik something they can work with?

```ruby
# frozen_string_literal: true

require "bundler/inline"
gemfile(true) do
  ruby "3.1.2"
  source "https://rubygems.org"
  gem "httparty", "0.21.0"
  gem "minitest", "5.17.0"
  gem "webmock", "3.18.1"
end

require 'webmock/minitest'
require 'minitest/autorun'

class BugTest < Minitest::Test
  MOCK_URL = 'http://www.example.com/api'

  def test_1
    stub_request(:post, MOCK_URL).to_return(
      body: "[]",
      status: 422,
      headers: { 'Content-Type' => 'application/json' }
    )
    HTTParty.post(MOCK_URL)
  end
end
```

**Comment by mikevoets** [comment]
@jaredbeck Sure thing!

Here's the repro script. The only notable difference here is that the response is an array literal `[]` instead of a stringified array:

```
# frozen_string_literal: true

require "bundler/inline"
gemfile(true) do
  ruby "2.7.6"
  source "https://rubygems.org"
  gem "httparty", "0.21.0"
  gem "minitest", "5.17.0"
  gem "webmock", "3.18.1"
end

require 'webmock/minitest'
require 'minitest/autorun'

class BugTest < Minitest::Test
  MOCK_URL = 'http://www.example.com/api'

  def test_1
    stub_request(:post, MOCK_URL).to_return(
      body: [],
      status: 422,
      headers: { 'Content-Type' => 'application/json' }
    )
    HTTParty.post(MOCK_URL)
  end
end
```

**Comment by splattael** [comment]
@mikevoets Thanks for the reproduction :bow: 

I've stumbled upon the same error when trying to [upgrade `httparty` at GitLab](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110245) :sweat: 

I've fixed it [by using a `String` for `body:`](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110245/diffs?commit_id=00036f78f136f4c6748b509d63755763bee9d290) in specs instead :muscle: 

I [am wondering](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/110245?commit_id=00036f78f136f4c6748b509d63755763bee9d290#note_1255412713) when `HTTPReponse#body` could NOT be a string :shrug: especially when used when used with `read_body { ... }` According the [Ruby docs it should return a string](https://rubyapi.org/2.7/o/net/httpresponse#method-i-body) :shrug: 

After reading the [implementation](https://github.com/ruby/ruby/blob/v2_7_7/lib/net/http/response.rb#L202) and [tests](https://github.com/ruby/ruby/blob/v2_7_7/test/net/http/test_httpresponse.rb) of Net::HTTP I see no evidence that body can be something else but a `String`.

WDYT?

@mikevoets @john-h-k Do you have a reproduction which happened in a real-world (non test/spec)? :thinking:

**Comment by john-h-k** [comment]
Nope, been purely on specs for me. I am trying that fix too. I am personally of the opinion it would make sense to change it to be non breaking, to make peoples lives' easier, but as it is outside of the proper usage I would also consider this issue resolved if that fix works for everyone + the maintainers decide they do not wish to change it

**Comment by mikevoets** [comment]
> Nope, been purely on specs for me. I am trying that fix too. I am personally of the opinion it would make sense to change it to be non breaking, to make peoples lives' easier, but as it is outside of the proper usage I would also consider this issue resolved if that fix works for everyone + the maintainers decide they do not wish to change it

Same for me - it only fails on tests.

**Comment by JonMidhir** [comment]
This patch would fix it. I tested with the benchmarking tool @TheSmartnik linked and it doesn't seem to reintroduce the memory leak:

```patch
diff --git a/lib/httparty/text_encoder.rb b/lib/httparty/text_encoder.rb
index 006893e..a8302d1 100644
--- a/lib/httparty/text_encoder.rb
+++ b/lib/httparty/text_encoder.rb
@@ -5,7 +5,7 @@ module HTTParty
     attr_reader :text, :content_type, :assume_utf16_is_big_endian
 
     def initialize(text, assume_utf16_is_big_endian: true, content_type: nil)
-      @text = +text
+      @text = +String(text)
       @content_type = content_type
       @assume_utf16_is_big_endian = assume_utf16_is_big_endian
     end
```

I think @splattael (:wave:) is right though. The specs/fixtures should be changed to use Strings instead of Arrays.

**Comment by jaredbeck** [comment]
The fault, dear Brutus, is not in our gems, but in our specs ..

sounds like we can close this one :)
