### ISSUE TITLE
NoMethodError: undefined method format

### ISSUE THREAD

**Issue by jlerpscher** [jnunemaker/httparty#401]
Hi,

I've just updated to 0.13.4 and things seems broken. I am working with ruby 2.2.2 and rails 4.2.1.

Any ideas?

```
HTTParty.get('http://www.google.fr')
NoMethodError: undefined method `format' for #<HTTParty::Response:0x007f951a3b36c8>
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/httparty-0.13.4/lib/httparty/response.rb:71:in `method_missing'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/httparty-0.13.4/lib/httparty/response.rb:40:in `inspect'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:110:in `start'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/console.rb:9:in `start'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Julien/ror/ozons/bin/rails:8:in `<top (required)>'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/commands/rails.rb:6:in `call'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:183:in `block in serve'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:156:in `fork'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:156:in `serve'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:131:in `block in run'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:125:in `loop'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application.rb:125:in `run'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spring-1.3.4/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/Julien/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'>> exit
```

**Comment by theB264** [comment]
Same issue here.  I updated to 0.13.4 and the same error.  I had to bump it back down and hold it at `"= 0.13.3"`

**Comment by saltvedt** [comment]
:+1:

**Comment by jnunemaker** [comment]
Testing to see if only a 2.2.2 issue. I'm not seeing it on other 2.x versions of ruby.

**Comment by jnunemaker** [comment]
Ah, I see it is only for inspect, not making the request. Ok thanks for reporting. I'm poking at it.

**Comment by jnunemaker** [comment]
Fixed by 2d2779e7555f2a0927d79ba7fdb37921c3310dd9.

**Comment by tilo** [comment]
this still happens for HTTParty 0.13.5 Rails 4.2.3  and Ruby 2.2.2 or 2.2.1 

NoMethodError: undefined method `debug_output' for #<Device:0x007ffd1732ab88>

But Device is not the class which I'm including HTTParty in.
