### ISSUE TITLE
httparty 0.15.2: incompatible encoding regexp match

### ISSUE THREAD

**Issue by maurosbu** [jnunemaker/httparty#533]
Hi folks,
I use httparty to interact with an API and I upgraded from v 0.14.x to v0.15.2.
Now I'm getting the following error:

    Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)`
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/parser.rb:120:in `gsub'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/parser.rb:120:in `json'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/parser.rb:140:in `parse_supported_format'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/parser.rb:105:in `parse'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/parser.rb:67:in `call'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/request.rb:383:in `parse_response'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/request.rb:351:in `block in handle_response'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/response.rb:25:in `parsed_response'
        from /home/app/bundle/gems/httparty-0.15.2/lib/httparty/response.rb:88:in `method_missing'

Environment details:
RubyOnRails 5.0.3
Ruby 2.3.3
Character encoding of API response is UTF-8 (checked in chrome developer tools with `document.characterSet`)

**Comment by martinsefcik** [comment]
The same issue on my side ... also after upgrading from 0.14.x to 0.15.x.

**Comment by martinsefcik** [comment]
It looks like it was introduced in #520

**Comment by siebertm** [comment]
This is definitely due to #520 and seems to be triggered when the server returns non-UTF-8 response.

**Comment by jnunemaker** [comment]
@Rsullivan00 any ideas on this? Or could anyone provide something I could create a spec from to work on a fix?

**Comment by NormandLemay** [comment]
In my side I do this to pass true:  `UTF8_BOM = "\xEF\xBB\xBF".force_encoding(Encoding::BINARY).freeze`

**Comment by Rsullivan00** [comment]
Damn 😦 . I might be able to take a look at this later today, and make sure that BOM stripping only happens with UTF-8 encoding.

**Comment by jnunemaker** [comment]
@normandlemay changing the constant does cause the specs to fail, but I don't quite get what you are suggesting I do.

**Comment by maurosbu** [comment]
This is part of the header of the response:

    {"content-type"=>["application/json; charset=utf-8"], "transfer-encoding"=>["chunked"], ... }

I hope it helps.

**Comment by lefty1975** [comment]
Any chance the following is also related to this issue:
I've recently updated from 0.14.0 to version 0.15.2 and when I try to execute a #delete I'm receiving the following stacktrace:

```
NoMethodError: undefined method `force_encoding' for nil:NilClass
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty/request.rb:280:in `encode_with_ruby_encoding'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty/request.rb:316:in `_encode_body'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty/request.rb:322:in `encode_body'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty/request.rb:350:in `handle_response'
from /Users//.rben`enter code here`v/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty/request.rb:158:in `perform'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty.rb:563:in `perform_request'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty.rb:520:in `delete'
from /Users/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/httparty-0.15.1/lib/httparty.rb:617:in `delete'
```
I reverted back to version 0.14.0 and the issue doesn't persist.

**Comment by Rsullivan00** [comment]
I'm unable to reproduce this in tests. I've tried to trigger the exception manually through forcing encoding to `ASCII-8BIT`, but haven't seen that encoding failure in any tests.

**Comment by maurosbu** [comment]
My API response does not contain UTF8 BOM. 
Code used to check if the BOM is present:
    
    curl API_ENDPOINT -o response.json
    has_bom() { head -c3 "$1" | grep -q $'\xef\xbb\xbf'; }
    has_bom response.json && echo yes

https://stackoverflow.com/questions/33977843/how-to-detect-if-a-file-has-a-utf-8-bom-in-bash

**Comment by lefty1975** [comment]
@Rsullivan00 Good Morning, I should have provided how or what I feel is in encountering this error message in 0.15.2. Please be patient with as I am not a developer, but trying my best to provide details that might assist in figuring out what might be causing this or if it is truly user error on my part.

When I try to execute the following:
`endpoint = "#{@token.baseURL}/api/file/document-type/#{$doc_type_id}"
    HTTParty.delete(endpoint, headers: { "Content-Type" => "application/json", "X-Requested-With" => "XMLHttpRequest", "Apikey" => @token.key, "Accept" => "application/json" })`

We don't return a body in the response for the verb of delete, so I'm not sure if this is causing issues or if I'm way off in left field.

**Comment by Rsullivan00** [comment]
@maurosbu I don't believe this is an issue with the BOM itself, just with my BOM-stripping regex being incompatible with some response encodings.

**Comment by jaypatrickhoward** [comment]
Could you test the encoding of the body before trying the gsub, and only do the gsub if it's UTF-8?  Or, alternately, force the encoding of the body to be UTF-8 before calling gsub on it?

**Comment by Rsullivan00** [comment]
@lefty1975, I think your issue is a separate issue.

Your failure is coming from `request.rb` calling a method on a `nil` body. Your `DELETE` response should have a body, unless you are returning a `204` response code.

**Comment by Rsullivan00** [comment]
@jaypatrickhoward Yeah, I think that's the way to go, but I'm trying to be able to reproduce the issue in a test so that I can ensure that I'm actually fixing it with that change, and any changes in the future don't re-introduce the issue.

**Comment by jaypatrickhoward** [comment]
What happens when the response body is empty (but not nil)?  Could that show up as ASCII-8BIT?

**Comment by NormandLemay** [comment]
This is my case response:
(byebug) response
`#<HTTParty::Response:0x7fb8aa79a698 parsed_response={"currencies"=>[{"code"=>"EUR", "options"=>{"locale"=>"en", "delimiter"=>"", "precision"=>2, "unit"=>"", "separator"=>".", "format"=>"%u%n €", "suffix"=>" €"}}, {"code"=>"CAD", "options"=>{"locale"=>"en", "delimiter"=>"", "precision"=>2, "unit"=>"", "separator"=>".", "format"=>"%u%n $", "suffix"=>" $"}}, {"code"=>"USD", "options"=>{"locale"=>"en", "delimiter"=>"", "precision"=>2, "unit"=>"", "separator"=>".", "format"=>"%u%n $", "suffix"=>" $"}}, {"code"=>"GBP", "options"=>{"locale"=>"en", "delimiter"=>"", "precision"=>2, "unit"=>"", "separator"=>".", "format"=>"%u%n £", "suffix"=>" £"}}, {"code"=>"CHF", "options"=>{"locale"=>"en", "delimiter"=>",", "precision"=>2, "unit"=>"CHF ", "separator"=>".", "format"=>"%u%n", "suffix"=>""}}]}, @response=#<Net::HTTPOK 200 OK readbody=true>, @headers={"x-frame-options"=>["SAMEORIGIN"], "x-xss-protection"=>["1; mode=block"], "x-content-type-options"=>["nosniff"], "x-ua-compatible"=>["chrome=1"], "content-type"=>["application/json; charset=utf-8"], "etag"=>["\"00004e3a0e92ab196e1d25582243e11e\""], "cache-control"=>["max-age=0, private, must-revalidate"], "x-request-id"=>["71f9be6a-ba9c-4dd7-9b60-4e110876eb86"], "x-runtime"=>["0.066780"], "connection"=>["close"], "server"=>["thin 1.6.1 codename Death Proof"]}>`

response.body.encoding => #<Encoding:ASCII-8BIT>

**Comment by Rsullivan00** [comment]
@NormandLemay awesome, I'm able to reproduce the issue with 

```
[39] pry(main)> raw_response
=> "{\"currencies\":[{\"code\":\"EUR\",\"options\":{\"locale\":\"en\",\"delimiter\":\"\",\"precision\":2,\"unit\":\"\",\"separator\":\".\",\"format\":\"%u%n \xE2\x82\xAC\",\"suffix\":\" \xE2\x82\xAC\"}},{\"code\":\"CAD\",\"options\":{\"locale\":\"en\",\"delimiter\":\"\",\"precision\":2,\"unit\":\"\",\"separator\":\".\",\"format\":\"%u%n $\",\"suffix\":\" $\"}},{\"code\":\"USD\",\"options\":{\"locale\":\"en\",\"delimiter\":\"\",\"precision\":2,\"unit\":\"\",\"separator\":\".\",\"format\":\"%u%n $\",\"suffix\":\" $\"}},{\"code\":\"GBP\",\"options\":{\"locale\":\"en\",\"delimiter\":\"\",\"precision\":2,\"unit\":\"\",\"separator\":\".\",\"format\":\"%u%n \xC2\xA3\",\"suffix\":\" \xC2\xA3\"}},{\"code\":\"CHF\",\"options\":{\"locale\":\"en\",\"delimiter\":\",\",\"precision\":2,\"unit\":\"CHF \",\"separator\":\".\",\"format\":\"%u%n\",\"suffix\":\"\"}}]}"
[40] pry(main)> raw_response.encoding
=> #<Encoding:ASCII-8BIT>
[41] pry(main)> raw_response.gsub(/\A#{UTF8_BOM}/, '')
Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
from (pry):41:in `gsub'
```

**Comment by Rsullivan00** [comment]
@NormandLemay, can you try using my branch in this PR to make sure it resolves your issue? https://github.com/jnunemaker/httparty/pull/538

**Comment by NormandLemay** [comment]
@Rsullivan00 , Yes your branch fix the error in my side

**Comment by lefty1975** [comment]
@Rsullivan00 we're returning a 204 response.

**Comment by Rsullivan00** [comment]
@lefty1975 In that case, it sounds like a bug. You should open a new issue.

**Comment by Rsullivan00** [comment]
@lefty1975 Did you try using the latest changes from master? I think that PR I linked might fix your issue.

**Comment by lefty1975** [comment]
@Rsullivan00 My apologies, I just saw the change you made and will try the latest version.

**Comment by Rsullivan00** [comment]
No worries. It wasn't my fix that will help you, it was https://github.com/jnunemaker/httparty/pull/530

**Comment by jnunemaker** [comment]
0.15.4 is out and should help with this.

**Comment by epardx** [comment]
This is what worked for me when I attempted to remove the BOM bytes from a UTF-8 string on the server side in a csv file content:

csv_text.gsub!("\xEF\xBB\xBF".force_encoding(Encoding::BINARY), '')

tip from NormandLemay above
